build:
  nodes:
    coverage:
      tests:
        override:
        - command: php ./vendor/bin/phpunit ./tests --coverage-clover './reports/clover.xml'
          coverage:
            file: ./reports/clover.xml
            format: clover